GOOSE_DBSTRING := "postgres://postgres:postgres@localhost:5432/db05?sslmode=disable"
GOOSE_MIGRATION_DIR := "migrations"

# All recipes
default:
    @just --list

# Run server application
run-server:
    go run cmd/server/main.go

# Run client application
run-client:
    go run cmd/client/main.go

# List applied and pending migrations
migrate-status:
    goose -dir {{GOOSE_MIGRATION_DIR}} postgres {{GOOSE_DBSTRING}} status

# Migrate to the latest version
migrate-up:
    goose -dir {{GOOSE_MIGRATION_DIR}} postgres {{GOOSE_DBSTRING}} up

# Rollback the most recent migration
migrate-down:
    goose -dir {{GOOSE_MIGRATION_DIR}} postgres {{GOOSE_DBSTRING}} down-to 0

# Create new migration files
migrate-create NAME:
    goose -dir {{GOOSE_MIGRATION_DIR}} create {{NAME}} sql

# Generate gRPC code from proto files
grpc-gen:
    mkdir -p api/pb

    protoc --proto_path=api/proto \
        --go_out=api/pb --go_opt=paths=source_relative \
        --go-grpc_out=api/pb --go-grpc_opt=paths=source_relative \
        api/proto/user/*.proto
